language: ruby
rvm:
    - 2.6

before_script:
    - chmod +x ./_scripts/*.sh

addons:
    apt:
        packages:
            - libcurl4-openssl-dev
            - sshpass
                
install:
    - gem install bundle

cache: bundler # caching bundler gem packages will speed up build    

script:
    - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./_scripts/test.sh; fi'
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./_scripts/test.sh && ./_scripts/deploy.sh; fi'

notifications:
    email: false

branches:
    only: 
        - master