language: ruby
rvm:
    - 2.6

before_script:
    - chmod +x ./_scripts/*.sh

addons:
    apt:
        packages:
            - libcurl4-openssl-dev
            - sshpass
                
install:
    - gem install bundle

cache: bundler # caching bundler gem packages will speed up build    

script: ./_scripts/test.sh && ./_scripts/deploy.sh

notifications:
    email: false

branches:
    only: 
        - master